"""Initial schema Update

Revision ID: 01317beee1c2
Revises: 11fd321b3e3b
Create Date: 2025-11-15 19:55:18.645960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01317beee1c2'
down_revision: Union[str, Sequence[str], None] = '11fd321b3e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('food_items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.create_foreign_key(None, 'food_items', 'categories', ['category_id'], ['id'])
    op.drop_column('food_items', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.drop_column('food_items', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
