"""create models tables

Revision ID: bb05e81cccea
Revises: 9f156bcb03f9
Create Date: 2025-11-11 13:01:30.423225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb05e81cccea'
down_revision: Union[str, Sequence[str], None] = '9f156bcb03f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produce_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('produce_items', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produce_classifications_id'), 'produce_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_produce_classifications_name'), 'produce_classifications', ['name'], unique=True)
    op.create_index(op.f('ix_produce_classifications_year'), 'produce_classifications', ['year'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('meal_recipes',
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], )
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], )
    )
    op.add_column('food_items', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('food_items', 'source')
    op.drop_table('recipe_ingredients')
    op.drop_table('meal_recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_produce_classifications_year'), table_name='produce_classifications')
    op.drop_index(op.f('ix_produce_classifications_name'), table_name='produce_classifications')
    op.drop_index(op.f('ix_produce_classifications_id'), table_name='produce_classifications')
    op.drop_table('produce_classifications')
    # ### end Alembic commands ###
