"""add meals and food items tables

Revision ID: f0285b6925a1
Revises: 50c4a324d5b7
Create Date: 2025-11-08 07:19:31.445193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0285b6925a1'
down_revision: Union[str, Sequence[str], None] = '50c4a324d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=True)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meals_name'), 'meals', ['name'], unique=False)
    op.create_table('meal_foods',
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], )
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restrictions_id'), 'restrictions', ['id'], unique=False)
    op.create_table('user_food_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.Column('removed_count', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_food_history_id'), 'user_food_history', ['id'], unique=False)
    op.create_table('mealplan_meals',
    sa.Column('mealplan_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['mealplan_id'], ['meal_plans.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mealplan_meals')
    op.drop_index(op.f('ix_user_food_history_id'), table_name='user_food_history')
    op.drop_table('user_food_history')
    op.drop_index(op.f('ix_restrictions_id'), table_name='restrictions')
    op.drop_table('restrictions')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_table('meal_foods')
    op.drop_index(op.f('ix_meals_name'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
